[project]
name = "coffee-with-claude"
version = "0.1.0"
description = "Claude interviews other models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.0.0",
    "python-dotenv>=1.0.0"
]
